version: '3.8'
services:
  ingress:
    image: nginx:stable-alpine
    container_name: ingress
    networks:
      - gateway
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      # - ./nginx-bad.conf:/etc/nginx/nginx.conf
      - ./nginx-good.conf:/etc/nginx/nginx.conf
      - ./site-content:/var/www/html 

networks:
  gateway: {}

